apiVersion: v1
kind: Secret
metadata:
    name: mastodon-secrets
    namespace: mastodon
type: Opaque
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:dCtNwVtHfhxXAMZGEDm3LsEo9Yzp3SXzbAwqnClAX7i3towMBNq1lmhUDdYdNrCs0bBR8vh7H0Cau8OWVCUJflH6nvyStLh8UB2Q6sjHWJICZ3h7MwxD/lDzfHIMoWY0Xbjf1TQlyRu7yfvtUPqfvre4VsA1YUXsi8EL1eW0M5M=,iv:QNXSda60qTXSUK6xA5rmEnB019Zw5DEPBJUVF0ceYVE=,tag:FFC253JEG8pTgKgZSkLheA==,type:str]
    OTP_SECRET: ENC[AES256_GCM,data:zwJngMh+y44wXCB0UWQF/OcFO/DH0ZpkrkK65VbrfexrcOTJilO2fOOYOOOROt/rYEffPTz1dhg6T5YOmSABWcuxjfMgpwc+Zo9Fx4YIhnJCILPSQ3R2gX8C3md30CyjuV8d5aK8qZzr9zXq+Jg2k8DjhwoC9UqObGSXBN4pn+A=,iv:hREOc0ZAxg3SOlOe8NQM38YgZ1eI6z8W3MoyriSw28c=,tag:lr24FDJ6Liw0ZMR8qf4TwQ==,type:str]
    VAPID_PRIVATE_KEY: ENC[AES256_GCM,data:uKiU9utBifdj/M8dkjPPJBnaH/h2/x2nICpwyjrBR78K58xw9FTaSz/tQfE=,iv:ohKEF4JZi7Mfx8Af9MimP5LURoPiXmsQK4KO7Vdn/LQ=,tag:PJkXTac3c5P/5pHnU6ltmQ==,type:str]
    VAPID_PUBLIC_KEY: ENC[AES256_GCM,data:x3hbBMC8iCaEzOAounb7aVgsnQ+Hhv14atohIH6gtPY8Kdg3sluuyXacQeeL3M4p2LcK0oOCQMCot/ToqlAvHDtZAiYcHEyVLOiXbmDi9F1lyrJTVcJ6Dg==,iv:GRxe95HGI1FdGX3m35O2E15RLayD5qI0dszMnmPqt/w=,tag:AGfGb0uwtKVv6UIWORYN3g==,type:str]
    login: ENC[AES256_GCM,data:Ri/t9WD3wVC0j/0ollegK7I04/0=,iv:Ltv6QMOai3pjlhf5aX28PfuQxBnnZsIxZFjRoXL5WXg=,tag:MH555kejeNNVkVL6cYqusg==,type:str]
    password: ENC[AES256_GCM,data:ELB1NMaFtr0sm/0c65et60ON1Nyy7HW/LGASPIOSp4S1w30PnoAiFhvXnj0=,iv:3qP+WODUnc63BQPiwE3A/IWCGfWew48npGZfJ0UhrnQ=,tag:gk2/6XVjlzCNFFRvBG5Epg==,type:str]
    redis-password: ENC[AES256_GCM,data:Q266fOxUgpACSsUIMtEtRClnr1JSH3Ur984Zv7/cEXQ=,iv:ew1Ec8kbHLWEUBE4pIkIbvJ9Uqx8rJDjGg3MCb6lO0g=,tag:FIl/g/G1QCL5gf88GMmJag==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:7wozu8VuxPTY4fa7bRlieJNHzCo=,iv:t356sCkBVvp/R/c2M6TUU6fDrHfyjyRHnquXvA6WzrM=,tag:SUFqHs63IX3yn43GBrUqyQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:WVrU7L39TDpU517kqqP3QUsNSTKlm5wE/OknmAWyj9Srrm0iZatqV72uIw==,iv:Wnt4DWWHcRRBRTsPi7MBk46di8rdzb+UvKt28Kkf1WM=,tag:QoJggjsEdrm5QY2p1gvQtQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19gj08c8zsqrgn3nkxdnf0m6cjmpruvrnnapvztjgja8nh3w5c9lqh4ag3d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKRW9jSzd0Qmoyb0ljalV6
            bnp5bVgyQmdwUlNHSTNVcDg3azN1c0JLT0VZCnkyOFF5cUxpQ3BMS0p4SkoxNFA2
            TG1oOVdoOTRtWTQ5czFkeVQ4d2FIRGMKLS0tIExZRXhwYVpmR25aSFJWVjFjQVVJ
            MmxNWE9LdVUzUlV4ZFFqdVVPN3grTG8KFBg9Fc9LV9HeqTLScnkcNNEHSLiro66V
            vQ52Rfj/7vYutvawx3XxxWcxyHxfSXp35pcpTveQ+YGp4wsco7RtIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-08-30T14:37:57Z"
    mac: ENC[AES256_GCM,data:D7Y/g4yhS0JUpWub+UlCPbdoQUaTpBKNtRzDkr1H5aH1qOkSWJUmtKhtXwP6Sqx0vO6/WZ8AIjaGGbFRbU2jSG5If4FAqA0XCu9sS8Emq0VIQ15ard50fss6kei03BoNoSdANi5gdnM4IsLdccZkZRrCiwlL1aay5t2XFg2DYeY=,iv:1EiJHY2MgI1Rv+e5FJr/whs1iFCSfRZy5gCjsqmDy1A=,tag:CszwZdn2kdVb+TwGzUgLbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
